### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by shatu** [microsoft/PyMarlin#53]
What PyTorch version does the latest PyMarlin release support? Since PyTorch has a fairly frequent release cycle with plenty of breaking changes, it would be good to specify the lower and upper bounds of the PyTorch version the PyMarlin library can support.

**Comment by jsleep** [comment]
That's a great question, I believe we've tested with PyTorch1.3-1.9 in our team - the day that PyTorch move 2.0+ there may be some breaking change that we need to adapt to

**Comment by shatu** [comment]
I see. Maybe we should then update the DockerFile to reflect this. Currently, it'll fetch the most recent version of PyTorch, which might start breaking things with newer versions of PyTorch.

**Comment by jsleep** [comment]
we don't even really use that Dockerfile but may be I can add torch<=1.9 in the required deps setup.py, pymarlin depends completely on pytorch being installed and we should have some strict dependency on it (even if it hasn't been installed yet).
