### ISSUE TITLE
Custom Argparser doesn't support multi-level commandline override

### ISSUE THREAD

**Issue by shatu** [microsoft/PyMarlin#59]
Custom argparser throws an exception when a multi-level nested config.yaml file is provided, and some of the nested parameters are overridden through commandline.

I believe it is because of the hard-coded assumption of a single-level nesting in the custom argparser. Some examples:
https://github.com/microsoft/PyMarlin/blob/11bce75626c322b749d3171d2e85ef84d0b95aef/pymarlin/utils/config_parser/custom_arg_parser.py#L135

https://github.com/microsoft/PyMarlin/blob/11bce75626c322b749d3171d2e85ef84d0b95aef/pymarlin/utils/config_parser/custom_arg_parser.py#L146

Example of multi-level nesting:
![image](https://user-images.githubusercontent.com/892650/130701544-92969872-7468-4490-8f20-8782738a20c6.png)

**Comment by jsleep** [comment]
Assigning to @ananthrs1 who set up the custom arg parser. I think we need to catch this in the command line parsing, probably only to further split up sections down to one more level (and just for module).

**Comment by ananthrs1** [comment]
Fixed in this PR: https://github.com/microsoft/PyMarlin/pull/60
