### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by shatu** [microsoft/PyMarlin#64]
PyMarlin is now available in pypi -- the installation documentation should be updated to reflect this.
https://marlin-docs.azurewebsites.net/installation.html

![image](https://user-images.githubusercontent.com/892650/134574114-b07fb563-a50d-4a24-aabe-2439602c3918.png)

**Comment by jsleep** [comment]
https://marlin-docs.azurewebsites.net/installation.html is not the official website anymore.

https://microsoft.github.io/PyMarlin/docs/installation is where the latest documentation for PyMarlin is now hosted (and linked to in our root README).
